# which benchmarks to run
benchmarks = '../../benchmarks/mem/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.opt]
pipeline = [
  "bril2json",
  "python to_ssa.py",
  "python ssa_to.py",
  "brili -p {args}",
]

[runs.memopt]
pipeline = [
  "bril2json",
  "python to_ssa.py",
  "python memopt.py",
  "python ssa_to.py",
  "brili -p {args}",
]
