# which benchmarks to run
benchmarks = '../../benchmarks/core/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.ssa]
pipeline = [
  "bril2json",
  "python to_ssa.py",
  "brili -p {args}",
]

[runs.final]
pipeline = [
  "bril2json",
  "python to_ssa.py",
  "python ssa_to.py",
  "brili -p {args}",
]
